"use client";

import { Award, ChevronRight, Clock3, PackageCheck, Sparkles, Star, Trophy } from "lucide-react";
import { useState } from "react";
import type { ProfileExperienceData } from "@/lib/profiles/experience";

const roleLabel = { customer: "Cliente", courier: "Cadete", admin: "Administrador" };
const statusLabel: Record<string, string> = { delivered: "Entregado", confirmed: "Disponible", assigned: "Asignado", heading_to_pickup: "En retiro", at_pickup: "En retiro", picked_up: "Retirado", heading_to_delivery: "En camino", at_delivery: "En destino", incident: "Incidencia", pending_confirmation: "Pendiente", cancelled: "Cancelado" };

export function ProfileExperience({ name, email, data }: { name: string; email?: string | null; data: ProfileExperienceData }) {
  const [tab, setTab] = useState<"summary" | "activity" | "achievements">("summary");
  const progress = data.nextLevelPoints ? Math.min(100, Math.round((data.points / data.nextLevelPoints) * 100)) : 100;
  const stars = Math.max(1, Math.min(5, Math.ceil(data.total / 3)));

  return <section className="mt-5 w-full overflow-hidden rounded-2xl border border-brand/20 bg-zinc-900 sm:mt-7">
    <div className="bg-gradient-to-br from-brand/20 via-zinc-900 to-zinc-900 p-4 sm:p-6">
      <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
        <div className="flex min-w-0 items-center gap-3 sm:items-start sm:gap-4"><div className="grid size-12 shrink-0 place-items-center rounded-2xl bg-brand text-lg font-black text-brand-foreground sm:size-14 sm:text-xl">{name.slice(0, 1).toUpperCase()}</div><div className="min-w-0"><p className="text-xs font-bold uppercase tracking-wider text-brand">Perfil {roleLabel[data.role]}</p><h1 className="mt-1 break-words text-xl font-bold sm:text-2xl">{name}</h1>{email && <p className="mt-1 break-all text-xs text-zinc-400 sm:text-sm">{email}</p>}</div></div>
        <div className="flex items-center justify-between rounded-xl border border-amber-300/25 bg-amber-300/10 px-3 py-2 sm:block sm:px-4 sm:py-3 sm:text-right"><p className="flex gap-1 text-amber-300 sm:justify-end">{Array.from({ length: 5 }, (_, index) => <Star key={index} className={`size-4 ${index < stars ? "fill-current" : "opacity-25"}`}/>)}</p><p className="text-sm font-bold sm:mt-1">{data.level}</p></div>
      </div>
      <div className="mt-5 grid grid-cols-2 gap-2 sm:mt-6 sm:grid-cols-4 sm:gap-3"><Metric label="Pedidos" value={data.total} icon={<PackageCheck className="size-4"/>}/><Metric label="Completados" value={data.completed} icon={<Trophy className="size-4"/>}/><Metric label="En curso" value={data.active} icon={<Clock3 className="size-4"/>}/><Metric label={data.highlightLabel} value={data.highlightValue} icon={<Sparkles className="size-4"/>}/></div>
    </div>
    <div className="grid grid-cols-3 border-y border-white/10"><Tab active={tab === "summary"} onClick={() => setTab("summary")}>Resumen</Tab><Tab active={tab === "activity"} onClick={() => setTab("activity")}>Actividad</Tab><Tab active={tab === "achievements"} onClick={() => setTab("achievements")}>Logros</Tab></div>
    <div className="p-4 sm:p-6">{tab === "summary" && <div className="grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><div><p className="flex items-center gap-2 font-bold"><Award className="size-5 shrink-0 text-brand"/>Tu progreso</p><p className="mt-2 text-sm text-zinc-400">Sumás puntos con cada operación completada. El nivel refleja tu actividad real en la plataforma.</p><div className="mt-5 rounded-xl bg-black/20 p-4"><div className="flex flex-col gap-1 text-sm sm:flex-row sm:items-center sm:justify-between sm:gap-3"><span className="font-bold">{data.points.toLocaleString("es-AR")} puntos</span><span className="text-zinc-400">{data.nextLevel}</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-zinc-700"><div className="h-full rounded-full bg-brand" style={{ width: `${progress}%` }}/></div><p className="mt-2 text-xs text-zinc-400">{data.nextLevelPoints > data.points ? `${data.nextLevelPoints - data.points} puntos para el próximo nivel.` : "Llegaste al nivel máximo."}</p></div></div><RecentActivity items={data.recent}/></div>}{tab === "activity" && <RecentActivity items={data.recent} expanded/>}{tab === "achievements" && <div className="grid gap-3 sm:grid-cols-3"><Achievement active={data.total >= 1} title="Primer paso" text="Registraste tu primera operación."/><Achievement active={data.completed >= 3} title="Constancia" text="Completaste 3 operaciones."/><Achievement active={data.completed >= 10} title="Nivel experto" text="Completaste 10 operaciones."/></div>}</div>
  </section>;
}

function Metric({ label, value, icon }: { label: string; value: string | number; icon: React.ReactNode }) { return <div className="min-w-0 rounded-xl border border-white/10 bg-black/15 p-3"><p className="flex min-w-0 items-center gap-1.5 text-xs text-zinc-400">{icon}<span className="truncate">{label}</span></p><p className="mt-2 break-words text-lg font-bold capitalize sm:text-xl">{value}</p></div>; }
function Tab({ active, onClick, children }: { active: boolean; onClick: () => void; children: React.ReactNode }) { return <button onClick={onClick} className={`border-b-2 px-1 py-3 text-xs font-semibold sm:py-4 sm:text-sm ${active ? "border-brand text-brand" : "border-transparent text-zinc-400"}`}>{children}</button>; }
function Achievement({ active, title, text }: { active: boolean; title: string; text: string }) { return <article className={`rounded-xl border p-4 ${active ? "border-brand/35 bg-brand/5" : "border-white/10 opacity-50"}`}><Trophy className="size-5 text-brand"/><h2 className="mt-3 font-bold">{title}</h2><p className="mt-1 text-sm text-zinc-400">{text}</p></article>; }
function RecentActivity({ items, expanded = false }: { items: ProfileExperienceData["recent"]; expanded?: boolean }) { const visible = expanded ? items : items.slice(0, 3); return <div><p className="font-bold">Actividad reciente</p><div className="mt-3 divide-y divide-white/10 rounded-xl border border-white/10">{visible.length ? visible.map((item) => <article className="grid gap-2 p-3 text-sm sm:grid-cols-[1fr_auto_auto] sm:items-center sm:gap-3" key={item.code}><div className="min-w-0"><p className="break-words font-semibold">{item.code}</p><p className="mt-1 text-xs text-zinc-500">{new Date(item.createdAt).toLocaleDateString("es-AR")}</p></div><div className="flex items-center justify-between gap-3 sm:block sm:text-right"><p className="text-xs text-brand">{statusLabel[item.status] ?? item.status}</p>{item.amount !== null && <p className="mt-1 text-xs text-zinc-400">${Number(item.amount).toLocaleString("es-AR")}</p>}</div><ChevronRight className="hidden size-4 text-zinc-500 sm:block"/></article>) : <p className="p-4 text-sm text-zinc-400">Aún no hay actividad registrada.</p>}</div></div>; }
