"use client";
import { useEffect, useState } from "react";
import { useForm, useWatch, type FieldErrors, type UseFormRegister, type UseFormRegisterReturn } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { Bike, BriefcaseBusiness, FileText, Package, ShoppingBag } from "lucide-react";
import { AddressPicker } from "@/components/maps/address-picker";
import { orderDraftSchema, type OrderDraft } from "@/features/orders/schema";

const steps = ["Servicio", "Retiro", "Entrega", "Precio"];
const services = [{ value:"document",label:"Documento",detail:"Sobres y papeles",Icon:FileText },{ value:"package",label:"Paquete",detail:"Hasta 15 kg",Icon:Package },{ value:"purchase",label:"Compra",detail:"Compramos por vos",Icon:ShoppingBag },{ value:"store_pickup",label:"Retiro",detail:"En un comercio",Icon:BriefcaseBusiness },{ value:"errand",label:"Trámite",detail:"Gestiones simples",Icon:Bike },{ value:"other",label:"Otro",detail:"Contanos qué necesitás",Icon:Package }] as const;
const emptyAddress = () => ({ formattedAddress:"", placeId:"", latitude:0, longitude:0, city:"", province:"", postalCode:"", streetNumber:"", floor:"", apartment:"", reference:"", mapConfirmed:false });
const defaultValues: OrderDraft = { serviceType:"document", product:{ fragile:false, requiresPurchaseFunds:false, requiresReceipt:false }, pickup:emptyAddress(), delivery:emptyAddress(), senderName:"", senderEmail:"", senderPhone:"", recipientName:"", recipientPhone:"", deliverySchedule:"immediate", scheduledDate:"", scheduledSlot:"", paymentResponsible:"sender", paymentMethod:"cash", urgent:false, termsAccepted:false, idempotencyKey:"00000000-0000-4000-8000-000000000000" };

export function OrderWizard() {
  const [step,setStep]=useState(0); const [notice,setNotice]=useState(""); const [attempted,setAttempted]=useState(false); const [estimate,setEstimate]=useState<EstimateResponse>(); const [trackingCode,setTrackingCode]=useState(""); const [submitting,setSubmitting]=useState(false);
  const form=useForm<OrderDraft>({resolver:zodResolver(orderDraftSchema),defaultValues}); const draft=useWatch({control:form.control}); const serviceType=useWatch({control:form.control,name:"serviceType"}); const schedule=useWatch({control:form.control,name:"deliverySchedule"});
  useEffect(()=>{const saved=localStorage.getItem("delivery-now-order-draft"); if(saved){try{form.reset(JSON.parse(saved) as OrderDraft)}catch{localStorage.removeItem("delivery-now-order-draft")}}},[form]);
  useEffect(()=>{localStorage.setItem("delivery-now-order-draft",JSON.stringify(draft))},[draft]);
  const fieldsForStep = () => step===0 ? ["serviceType","product"] as const : step===1 ? ["pickup","senderName","senderPhone"] as const : step===2 ? ["delivery","recipientName","recipientPhone","deliverySchedule","scheduledDate","scheduledSlot","paymentResponsible"] as const : ["senderEmail","termsAccepted"] as const;
  const next=async()=>{ setAttempted(true); const valid=await form.trigger(fieldsForStep()); if(!valid){setNotice("Completá los campos marcados para continuar."); return;} setAttempted(false); setNotice(""); if(step===2){setSubmitting(true);try{const response=await fetch("/api/orders/estimate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form.getValues())});const payload=await response.json() as EstimateResponse|{message:string};if(!response.ok)throw new Error("message" in payload?payload.message:"No se pudo calcular el precio");setEstimate(payload as EstimateResponse);setStep(3)}catch(error){setNotice(error instanceof Error?error.message:"No se pudo calcular el precio")}finally{setSubmitting(false)};return;} if(step===3){setSubmitting(true);try{const response=await fetch("/api/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form.getValues())});const payload=await response.json() as {trackingCode?:string;message?:string};if(!response.ok||!payload.trackingCode)throw new Error(payload.message??"No se pudo confirmar el pedido");localStorage.removeItem("delivery-now-order-draft");setTrackingCode(payload.trackingCode)}catch(error){setNotice(error instanceof Error?error.message:"No se pudo confirmar el pedido")}finally{setSubmitting(false)};return;} setStep(step+1);};
  const error=form.formState.errors;
  if(trackingCode)return <section className="mt-8 rounded-2xl border border-emerald-500/30 bg-zinc-900 p-7"><p className="font-bold text-emerald-400">SOLICITUD CONFIRMADA</p><h2 className="mt-2 text-2xl font-bold">Tu código es {trackingCode}</h2><p className="mt-3 text-zinc-300">Te enviamos el seguimiento y PIN de entrega al correo indicado.</p></section>;
  return <form className="mt-8 rounded-2xl border border-white/10 bg-[#17191c] p-4 shadow-2xl sm:p-7" noValidate><StepHeader step={step}/>{step===0&&<ServiceStep register={form.register} selected={serviceType} errors={error}/>} {step===1&&<PickupStep form={form} errors={error} showErrors={attempted}/>} {step===2&&<DeliveryStep form={form} schedule={schedule} errors={error} showErrors={attempted}/>} {step===3&&<ConfirmationStep form={form} errors={error} estimate={estimate}/>} {notice&&<p role="status" className="mt-5 rounded-lg bg-yellow-400/10 p-3 text-sm text-yellow-100">{notice}</p>}<div className="mt-8 flex justify-between border-t border-white/10 pt-5"><button type="button" disabled={!step||submitting} onClick={()=>{setAttempted(false);setStep(step-1)}} className="rounded-lg px-4 py-3 text-sm disabled:opacity-40">Volver</button><button type="button" disabled={submitting} onClick={next} className="rounded-lg bg-yellow-400 px-5 py-3 text-sm font-bold text-black disabled:opacity-50">{submitting?"Procesando…":step===3?"Confirmar solicitud":"Continuar"}</button></div></form>;
}
type EstimateResponse={distanceMeters:number;durationSeconds:number;price:{basePrice:number;extraKm:number;pricePerExtraKm:number;serviceSurcharge:number;total:number};priceStatus:string};
function StepHeader({step}:{step:number}){return <ol className="mb-8 flex justify-between gap-1">{steps.map((label,index)=><li key={label} className="flex flex-1 flex-col items-center gap-2 text-center text-xs"><span className={index<=step?"grid size-7 place-items-center rounded-full bg-yellow-400 font-black text-black":"grid size-7 place-items-center rounded-full bg-zinc-700 text-zinc-400"}>{index+1}</span><span className={index===step?"font-bold":"text-zinc-500"}>{label}</span></li>)}</ol>}
function ServiceStep({register,selected,errors}:{register:UseFormRegister<OrderDraft>;selected:OrderDraft["serviceType"];errors:FieldErrors<OrderDraft>}){const packageFlow=selected==="package"; const needsDescription=selected!=="document"; return <fieldset><legend className="text-xl font-bold">¿Qué necesitás enviar?</legend><p className="mt-1 text-sm text-zinc-400">Elegí el servicio y te pedimos solo los datos necesarios.</p><div className="mt-5 grid gap-3 sm:grid-cols-2">{services.map(({value,label,detail,Icon})=><label key={value} className={selected===value?"flex cursor-pointer gap-3 rounded-xl border border-yellow-400 bg-yellow-400/10 p-4":"flex cursor-pointer gap-3 rounded-xl border border-white/10 bg-zinc-900 p-4"}><input className="sr-only" type="radio" value={value} {...register("serviceType")}/><Icon className="mt-1 size-5 text-yellow-400"/><span><strong className="block">{label}</strong><small className="text-zinc-400">{detail}</small></span></label>)}</div>{needsDescription&&<Field label="¿Qué debemos retirar, comprar o entregar?" error={errors.product?.description?.message} registration={register("product.description")} placeholder="Ej. caja con repuestos para bicicleta"/>}{packageFlow&&<div className="mt-4 grid gap-4 sm:grid-cols-2"><SelectField label="Tamaño aproximado" error={errors.product?.size?.message} registration={register("product.size")} options={[["","Elegí una opción"],["small","Pequeño: sobre o caja chica"],["medium","Mediano: mochila o caja media"],["large","Grande: requiere confirmación"]]}/><Field label="Peso aproximado (kg)" type="number" error={errors.product?.weightKg?.message} registration={register("product.weightKg",{valueAsNumber:true})}/></div>}{selected==="purchase"&&<div className="mt-4 rounded-xl bg-zinc-900 p-4"><label className="flex gap-2 text-sm"><input type="checkbox" {...register("product.requiresPurchaseFunds")}/>Necesito que el cadete lleve dinero para comprar</label><Field label="Monto aproximado de compra" type="number" error={errors.product?.purchaseFunds?.message} registration={register("product.purchaseFunds",{valueAsNumber:true})}/></div>}<div className="mt-4 flex flex-wrap gap-4 text-sm"><label><input type="checkbox" {...register("product.fragile")}/> Frágil</label><label><input type="checkbox" {...register("product.requiresReceipt")}/> Requiere comprobante</label></div><Field label="Observaciones (opcional)" error={errors.product?.notes?.message} registration={register("product.notes")} placeholder="Ej. tocar timbre B"/></fieldset>}
function PickupStep({form,errors,showErrors}:{form:ReturnType<typeof useForm<OrderDraft>>;errors:FieldErrors<OrderDraft>;showErrors:boolean}){return <fieldset className="grid gap-4"><legend className="text-xl font-bold">Punto de retiro</legend><p className="text-sm text-zinc-400">Seleccioná una sugerencia y confirmá el punto en el mapa.</p><AddressPicker name="pickup" label="¿Desde dónde retiramos?" setValue={form.setValue} value={form.getValues("pickup.formattedAddress")} error={showErrors&&!form.getValues("pickup.mapConfirmed") ? "Seleccioná una dirección sugerida dentro del radio de 20 km y confirmá el punto en el mapa." : errors.pickup?.root?.message||errors.pickup?.placeId?.message||errors.pickup?.mapConfirmed?.message||errors.pickup?.formattedAddress?.message}/><AddressExtras register={form.register} prefix="pickup"/><Field label="Nombre de quien entrega" error={errors.senderName?.message} registration={form.register("senderName")}/><Field label="Teléfono de contacto" error={errors.senderPhone?.message} registration={form.register("senderPhone")} placeholder="+54 9 336 412-3456"/></fieldset>}
function DeliveryStep({form,schedule,errors,showErrors}:{form:ReturnType<typeof useForm<OrderDraft>>;schedule:OrderDraft["deliverySchedule"];errors:FieldErrors<OrderDraft>;showErrors:boolean}){return <fieldset className="grid gap-4"><legend className="text-xl font-bold">Punto de entrega</legend><AddressPicker name="delivery" label="¿A dónde llevamos?" setValue={form.setValue} value={form.getValues("delivery.formattedAddress")} error={showErrors&&!form.getValues("delivery.mapConfirmed") ? "Seleccioná una dirección sugerida dentro del radio de 20 km y confirmá el punto en el mapa." : errors.delivery?.root?.message||errors.delivery?.placeId?.message||errors.delivery?.mapConfirmed?.message||errors.delivery?.formattedAddress?.message}/><AddressExtras register={form.register} prefix="delivery"/><Field label="Nombre de quien recibe" error={errors.recipientName?.message} registration={form.register("recipientName")}/><Field label="Teléfono de quien recibe" error={errors.recipientPhone?.message} registration={form.register("recipientPhone")} placeholder="+54 9 336 412-3456"/><div className="grid gap-3 sm:grid-cols-2"><SelectField label="¿Cuándo entregamos?" error={errors.deliverySchedule?.message} registration={form.register("deliverySchedule")} options={[["immediate","Entrega inmediata"],["scheduled","Programar para más tarde"]]}/><SelectField label="¿Quién paga el envío?" error={errors.paymentResponsible?.message} registration={form.register("paymentResponsible")} options={[["sender","Paga quien envía"],["recipient","Paga quien recibe"]]}/></div>{schedule==="scheduled"&&<div className="grid gap-3 sm:grid-cols-2"><Field label="Fecha" type="date" error={errors.scheduledDate?.message} registration={form.register("scheduledDate")}/><SelectField label="Franja horaria" error={errors.scheduledSlot?.message} registration={form.register("scheduledSlot")} options={[["","Elegí una franja"],["08:00-13:00","08:00 a 13:00"],["16:00-21:00","16:00 a 21:00"]]}/></div>}</fieldset>}
function AddressExtras({register,prefix}:{register:UseFormRegister<OrderDraft>;prefix:"pickup"|"delivery"}){return <div className="grid gap-3 sm:grid-cols-3"><Field label="Piso" registration={register(`${prefix}.floor`)}/><Field label="Depto." registration={register(`${prefix}.apartment`)}/><Field label="Referencia" registration={register(`${prefix}.reference`)} placeholder="Ej. portón negro"/></div>}
function ConfirmationStep({form,errors,estimate}:{form:ReturnType<typeof useForm<OrderDraft>>;errors:FieldErrors<OrderDraft>;estimate?:EstimateResponse}){const value=form.getValues();return <section><h2 className="text-xl font-bold">Precio y confirmación</h2><p className="mt-2 text-sm text-zinc-400">Precio confirmado según la ruta y tarifa vigente.</p><div className="mt-5 space-y-3 rounded-xl bg-zinc-900 p-4 text-sm"><p><span className="text-zinc-400">Retiro:</span> {value.pickup.formattedAddress}</p><p><span className="text-zinc-400">Entrega:</span> {value.delivery.formattedAddress}</p><p><span className="text-zinc-400">Distancia:</span> {estimate?(estimate.distanceMeters/1000).toFixed(1):"—"} km · {estimate?Math.ceil(estimate.durationSeconds/60):"—"} min</p><p><span className="text-zinc-400">Base:</span> ${estimate?.price.basePrice.toLocaleString("es-AR")??"—"}</p><p><span className="text-zinc-400">Adicional por distancia:</span> ${estimate?Math.round(estimate.price.extraKm*estimate.price.pricePerExtraKm).toLocaleString("es-AR"):"—"}</p><p><span className="text-zinc-400">Servicio:</span> ${estimate?.price.serviceSurcharge.toLocaleString("es-AR")??"—"}</p><p className="border-t border-white/10 pt-3 text-base font-bold text-yellow-400">Total confirmado: ${estimate?.price.total.toLocaleString("es-AR")??"—"}</p></div><Field label="Correo para seguimiento y comprobante" type="email" error={errors.senderEmail?.message} registration={form.register("senderEmail")}/><div className="mt-4 flex flex-wrap gap-4 text-sm"><label><input type="checkbox" {...form.register("urgent")}/> Necesito urgencia</label><SelectField label="Forma de pago" error={errors.paymentMethod?.message} registration={form.register("paymentMethod")} options={[["cash","Efectivo"],["transfer","Transferencia"],["mercado_pago_manual","Mercado Pago"]]}/></div><label className="mt-5 flex gap-2 text-sm"><input type="checkbox" {...form.register("termsAccepted")}/>Acepto los términos y la política de privacidad.</label></section>}
function Field({label,registration,error,type="text",placeholder}:{label:string;registration:UseFormRegisterReturn;error?:string;type?:string;placeholder?:string}){return <label className="mt-4 grid gap-1 text-sm font-medium">{label}<input type={type} placeholder={placeholder} className="rounded-lg bg-zinc-900 px-4 py-3 outline-none ring-yellow-400 focus:ring-2" {...registration}/>{error&&<small role="alert" className="font-normal text-red-400">{error}</small>}</label>}
function SelectField({label,registration,error,options}:{label:string;registration:UseFormRegisterReturn;error?:string;options:string[][]}){return <label className="grid gap-1 text-sm font-medium">{label}<select className="rounded-lg bg-zinc-900 px-4 py-3" {...registration}>{options.map(([value,text])=><option key={value} value={value}>{text}</option>)}</select>{error&&<small role="alert" className="font-normal text-red-400">{error}</small>}</label>}
