"use client";

import { Bike, Check, LoaderCircle } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { authenticatedFetch } from "@/lib/auth/authenticated-fetch";

type TransportType = "bici" | "moto";
const options: Array<{ value: TransportType; label: string; description: string }> = [{ value: "bici", label: "Bicicleta", description: "Para entregas ágiles y cercanas." }, { value: "moto", label: "Moto", description: "Para mayor alcance y capacidad." }];

export function CourierTransportForm({ initialTransport }: { initialTransport: string | null }) {
  const router = useRouter();
  const initialValue: TransportType = initialTransport === "bici" ? "bici" : "moto";
  const [selected, setSelected] = useState<TransportType>(initialValue); const [saved, setSaved] = useState<TransportType>(initialValue); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function save() { setBusy(true); setMessage(""); try { const response = await authenticatedFetch("/api/courier/transport", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ transportType: selected }) }); const payload = await response.json() as { message?: string; transportType?: TransportType }; if (!response.ok || !payload.transportType) throw new Error(payload.message ?? "No pudimos actualizar tu movilidad."); setSaved(payload.transportType); setSelected(payload.transportType); setMessage("Movilidad actualizada. Tu panel operativo ya usa esta configuración."); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "No pudimos actualizar tu movilidad."); } finally { setBusy(false); } }
  return <section className="mt-5 rounded-2xl border border-white/10 bg-zinc-900 p-4 sm:mt-6 sm:p-6"><div className="flex items-start gap-3"><div className="grid size-10 shrink-0 place-items-center rounded-xl bg-brand/10 text-brand"><Bike className="size-5"/></div><div><h2 className="font-bold">Tu movilidad</h2><p className="mt-1 text-sm text-zinc-400">Elegí el medio que usás para repartir. Se verá igual en tu perfil y panel operativo.</p></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{options.map((option) => <button type="button" key={option.value} onClick={() => { setSelected(option.value); setMessage(""); }} disabled={busy} aria-pressed={selected === option.value} className={`rounded-xl border p-4 text-left transition focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-brand/20 disabled:opacity-60 ${selected === option.value ? "border-brand bg-brand/10" : "border-white/10 hover:border-white/25 hover:bg-white/5"}`}><span className="flex items-center justify-between gap-3"><span className="font-semibold">{option.label}</span>{selected === option.value && <Check aria-label="Seleccionado" className="size-4 text-brand"/>}</span><span className="mt-1 block text-sm text-zinc-400">{option.description}</span></button>)}</div><div className="mt-5 flex flex-wrap items-center gap-3"><button type="button" disabled={busy || selected === saved} onClick={() => void save()} className="inline-flex min-h-11 items-center gap-2 rounded-lg bg-brand px-4 py-2 text-sm font-bold text-brand-foreground disabled:cursor-not-allowed disabled:opacity-50">{busy && <LoaderCircle className="size-4 animate-spin"/>}{busy ? "Guardando…" : "Guardar movilidad"}</button>{message && <p role={message.startsWith("No pudimos") ? "alert" : "status"} className={`text-sm ${message.startsWith("No pudimos") ? "text-red-300" : "text-emerald-300"}`}>{message}</p>}</div></section>;
}
