create extension if not exists pgcrypto;
create type public.user_role as enum ('customer','courier','admin');
create type public.order_status as enum ('draft','pending_confirmation','confirmed','assigned','heading_to_pickup','at_pickup','picked_up','heading_to_delivery','at_delivery','delivered','cancelled','rejected','incident');
create type public.payment_status as enum ('pending','confirmed','partially_paid','failed','refunded');

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text, email text, phone_e164 text, role public.user_role not null default 'customer', avatar_url text, email_verified boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.customers (id uuid primary key default gen_random_uuid(), profile_id uuid unique references public.profiles(id) on delete cascade, created_at timestamptz not null default now());
create table public.service_types (id uuid primary key default gen_random_uuid(), code text unique not null, name text not null, active boolean not null default true, created_at timestamptz not null default now());
create table public.service_zones (id uuid primary key default gen_random_uuid(), name text not null, city text not null, province text not null, polygon_geojson jsonb not null, active boolean not null default true, surcharge numeric not null default 0, max_distance_km numeric, created_at timestamptz not null default now());
create table public.couriers (id uuid primary key default gen_random_uuid(), profile_id uuid unique not null references public.profiles(id), is_active boolean not null default true, is_online boolean not null default false, transport_type text not null, max_weight numeric not null default 10, service_zone_id uuid references public.service_zones(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.pricing_rules (id uuid primary key default gen_random_uuid(), base_price numeric not null check(base_price >= 0), included_km numeric not null check(included_km >= 0), price_per_extra_km numeric not null check(price_per_extra_km >= 0), minimum_price numeric not null check(minimum_price >= 0), configuration jsonb not null default '{}', valid_from timestamptz not null default now(), valid_to timestamptz, created_at timestamptz not null default now());
create table public.addresses (id uuid primary key default gen_random_uuid(), formatted_address text not null, place_id text not null, latitude double precision not null, longitude double precision not null, street text, street_number text, city text, province text, postal_code text, floor text, apartment text, reference text, created_at timestamptz not null default now());
create table public.orders (id uuid primary key default gen_random_uuid(), tracking_code text unique not null, customer_id uuid references public.customers(id), guest_name text, guest_email text, guest_phone_e164 text, service_type_id uuid not null references public.service_types(id), status public.order_status not null default 'pending_confirmation', assigned_courier_id uuid references public.couriers(id), payment_responsible text not null check(payment_responsible in ('sender','recipient')), payment_method text, payment_status public.payment_status not null default 'pending', delivery_pin_hash text not null, scheduled_at timestamptz, distance_meters integer, duration_seconds integer, estimated_price numeric, final_price numeric, price_snapshot jsonb not null, notes text, idempotency_key uuid unique not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), completed_at timestamptz, cancelled_at timestamptz);
create table public.order_stops (id uuid primary key default gen_random_uuid(), order_id uuid not null references public.orders(id) on delete cascade, type text not null check(type in ('pickup','delivery')), sequence smallint not null, address_id uuid not null references public.addresses(id), contact_name text not null, contact_phone_e164 text not null, instructions text, arrived_at timestamptz, completed_at timestamptz, unique(order_id, sequence));
create table public.order_status_history (id uuid primary key default gen_random_uuid(), order_id uuid not null references public.orders(id) on delete cascade, previous_status public.order_status, new_status public.order_status not null, changed_by uuid references public.profiles(id), reason text, metadata jsonb not null default '{}', created_at timestamptz not null default now());
create table public.notifications (id uuid primary key default gen_random_uuid(), user_id uuid references public.profiles(id), order_id uuid references public.orders(id), channel text not null, type text not null, title text not null, body text not null, payload jsonb not null default '{}', status text not null default 'pending', sent_at timestamptz, read_at timestamptz, error_message text, retry_count integer not null default 0, created_at timestamptz not null default now());
create table public.delivery_proofs (id uuid primary key default gen_random_uuid(), order_id uuid not null references public.orders(id), storage_path text not null, proof_type text not null, receiver_name text, pin_validated boolean not null default false, created_at timestamptz not null default now());
create table public.incidents (id uuid primary key default gen_random_uuid(), order_id uuid not null references public.orders(id), courier_id uuid references public.couriers(id), type text not null, description text not null, status text not null default 'open', created_at timestamptz not null default now());
create table public.audit_logs (id uuid primary key default gen_random_uuid(), actor_id uuid references public.profiles(id), action text not null, entity_type text not null, entity_id uuid, before_data jsonb, after_data jsonb, created_at timestamptz not null default now());

create index orders_tracking_code_idx on public.orders(tracking_code); create index orders_status_idx on public.orders(status); create index orders_created_at_idx on public.orders(created_at desc); create index orders_courier_idx on public.orders(assigned_courier_id); create index orders_customer_idx on public.orders(customer_id); create index order_stops_order_idx on public.order_stops(order_id); create index status_history_order_idx on public.order_status_history(order_id); create index notifications_user_status_idx on public.notifications(user_id,status);

create or replace function public.current_role() returns public.user_role language sql stable security definer set search_path=public as $$ select role from public.profiles where id=auth.uid() $$;
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$ select public.current_role()='admin' $$;
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,email,full_name) values(new.id,new.email,coalesce(new.raw_user_meta_data->>'full_name','')); insert into public.customers(profile_id) values(new.id); return new; end; $$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security; alter table public.customers enable row level security; alter table public.couriers enable row level security; alter table public.orders enable row level security; alter table public.order_stops enable row level security; alter table public.order_status_history enable row level security; alter table public.notifications enable row level security; alter table public.delivery_proofs enable row level security; alter table public.incidents enable row level security; alter table public.audit_logs enable row level security;
create policy profiles_own on public.profiles for select using (id=auth.uid() or public.is_admin()); create policy profiles_update_own on public.profiles for update using(id=auth.uid()) with check(id=auth.uid() and role=public.current_role());
create policy orders_customer_read on public.orders for select using (public.is_admin() or customer_id in(select id from public.customers where profile_id=auth.uid()) or assigned_courier_id in(select id from public.couriers where profile_id=auth.uid()));
create policy stops_authorized_read on public.order_stops for select using (exists(select 1 from public.orders o where o.id=order_id and (public.is_admin() or o.customer_id in(select id from public.customers where profile_id=auth.uid()) or o.assigned_courier_id in(select id from public.couriers where profile_id=auth.uid()))));
create policy notifications_own on public.notifications for select using(user_id=auth.uid() or public.is_admin());
-- All writes to orders, statuses, proofs and audit logs happen through server-side RPCs with service credentials.
-- Create private buckets delivery-proofs, incident-evidence and profile-images in Supabase Dashboard; do not create public bucket policies.
